# Generated by Django 5.0.1 on 2024-01-31 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_image',
            new_name='feature_image',
        ),
    ]
